lba/urls.py
from django.urls import path
from . import views


app_name = "lba"

urlpatterns = [
    path('', views.home, name='home'),
    path('helloworld', views.helloworld, name='helloworld'),
    path('artist/<str:artist_name>/', views.artist, name='artist'),    
    path('album/<str:album_id>/', views.album, name='album'),    
]



'''
************************************************************
******* VENV ***********************************************
************************************************************

C:\ZLOCAL\VENV\SCRIPTS\activate.ps1
CD C:\ZLOCAL\lba\
python manage.py runserver


C:\ZDEPOT\VENV\SCRIPTS\deactivate


pip freeze > requirements.txt
pip install -r requirements.txt


'''

root/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lba/', include('lba.urls')),
]

lba/models.py
from django.db import models


# Create your models here.
class Artist(models.Model):
    code = models.CharField(max_length=100, verbose_name="Code")
    name = models.CharField(max_length=100, verbose_name="Nom")

    def __str__(self):
        return self.name











'''
python manage.py makemigrations lba

python manage.py sqlmigrate lab 0001

python manage.py migrate
'''

lba/views.py
from django.shortcuts import render
from .models import Artist
from .api_spotify import *

# Create your views here.
from django.http import HttpResponse

def test(request):    
    return HttpResponse("test Hello World")

def helloworld(request):        
    return render(request, "lba/helloworld.html")

def home(request):
    artists = Artist.objects.all()
    return render(request, "lba/home.html", {'artists': artists})

def artist(request, artist_name):
    datas = get_infos_artist(artist_name)
    return render(request, "lba/artist.html", {'datas' : datas})

def album(request, album_id):
    tracks = get_tracks_by_album(album_id)
    return render(request, "lba/album.html", {'tracks' : tracks})

lba/templates/lba/album.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Album</title>

    <style>
        body { font-family: Arial, sans-serif; text-align: center; }
        table { width: 50%; margin: auto; border-collapse: collapse; }
        th, td { border: 1px solid black; padding: 3px; }
    </style>

</head>


<body>

    <h1>Album</h1>

    <table>
        <tr>
            <th>Titre</th>
            <th>Durée</th>
            <!-- <th>Écouter sur spotify</th> -->
            <th>Écouter</th>
        </tr>
        
        {% for track in tracks %}
        <tr>
            <td style="text-align: left;">{{ track.name }}</td>
            <td>{{ track.duration_ms }}</td>
            <!-- <td><a href="https://open.spotify.com/track/{{ track.id }}" target="_blank">Écouter sur Spotify 🎵</a></td> -->
            <td><a href="#" class="track-link" data-track-id="{{ track.id }}">Play it</a></td>
        </tr>
        {% endfor %}

    </table>

    <br>
    
    <iframe 
        id="spotify-player" 
        src="https://open.spotify.com/embed/track/" 
        width="300" 
        height="80" 
        frameborder="0" 
        allowtransparency="true" 
        allow="encrypted-media"
        >
    </iframe>

    <script>
        document.querySelectorAll(".track-link").forEach(function(link) {
            link.addEventListener("click", function(event) {
                event.preventDefault();  // Empêcher l'action par défaut du lien

                var trackId = this.getAttribute("data-track-id");
                var iframe = document.getElementById("spotify-player");
                iframe.src = "https://open.spotify.com/embed/track/" + trackId;

                // iframe.src = "https://open.spotify.com/embed/track/" + trackId + "?autoplay=1";
                // document.querySelector('[title="Play"]');

                
            });
        });
    </script>


</body>
</html>

lba/templates/lba/artist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Artist</title>

    <style>
        body { font-family: Arial, sans-serif; text-align: center; }
        .album { display: inline-block; margin: 10px; text-align: center; }
        img { width: 150px; height: 150px; border-radius: 8px; }        
        .album img {transition: transform 0.3s ease-in-out;}
        .album img:hover {transform: scale(1.1);}
        .release_date {color: orange;font-size: small;}
    </style>

</head>
<body>
    <h1>ARTIST : {{ datas.artist.name }}</h1>
    <img src="{{ datas.artist.image }}" alt="{{ datas.artist.name }}">

    <h2>Albums</h2>
    {% for album in datas.albums %}
    <div class="album">
        
        {% if album.image %}
        <a href="{% url 'lba:album' album.id %}"> 
            <img src="{{ album.image }}" alt="{{ album.name }}">
        </a>
        {% endif %}
                
        <p>{{ album.name }}</p>
        
        <p class="release_date">{{ album.release_date }}</p>
        
    </div>
{% endfor %}    

</body>
</html>

lba/templates/lba/helloworld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello world</title>
</head>
<body>
    <h1>Hello world</h1>
    <p>c'est une page simple.</p>
    <p><strong>Je met du gras.</strong></p>
    <p style="color:rgb(0, 255, 0)">Je met du rouge.</p>
    <p>Oh lala</p>
</body>
</html>

lba/templates/lba/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acceuil</title>

    <style>
        table {            
            border-collapse: collapse;
            width: 50%;
        }
        td, th {
            border: 1px solid black;
            padding: 4px;
            text-align: left;
        }
    </style>

</head>
<body>
    
    <a href="{% url 'admin:index' %}" class="position-absolute top-0 end-0 m-2 text-muted small">
        Admin
    </a>

    <h1>Page d'Accueil</h1>
    
    <h2>Artistes</h2>

    <table>    
    {% for artist in artists %}
    <tr>
        <td>
            <a href="{% url 'lba:artist' artist.name %}">{{ artist.name }}</a>
        </td>
    </tr>
    {% endfor %}
</table>

</body>
</html>